SELECT *
FROM CUSTOMER
LIMIT 5;

-- Q1. What is the total revenue generated by male vs. female customers

SELECT GENDER,
	SUM(PURCHASE_AMOUNT) AS REVENUE
FROM CUSTOMER
GROUP BY GENDER;

-- Q2. Which customer used a discount but still spent more than average purchase amount?

SELECT CUSTOMER_ID,
	PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = 'Yes'
	AND PURCHASE_AMOUNT >=
		(SELECT AVG(PURCHASE_AMOUNT)
			FROM CUSTOMER);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT DISTINCT ITEM_PURCHASED,
	ROUND(AVG(REVIEW_RATING::numeric),
		2) AS "avg_rating"
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY AVG_RATING DESC
LIMIT 5 ;

-- Q4. Compare the average purchase amount between standard and express shipping?

SELECT SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT),
		2)
FROM CUSTOMER
WHERE SHIPPING_TYPE in ('Standard','Express')
group by shipping_type;

-- Q5. Do subsribed customers spend more? compare average spend and total revenue between subscribers and non subscribers?

SELECT SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
	AVG(PURCHASE_AMOUNT) AS AVG_SPEND,
	SUM(PURCHASE_AMOUNT) AS REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT ITEM_PURCHASED,
	ROUND(100 * SUM(CASE
																					WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
																					ELSE 0
																	END) / COUNT(*),
		2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

-- Q7. Segment customers into new, Returning and loyal based on their total number of previous purchases?
 WITH CUSTOMER_TYPE AS
	(SELECT CUSTOMER_ID,
			PREVIOUS_PURCHASES,
			CASE
							WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
							WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'Returning'
							ELSE 'Loyal'
			END AS CUSTOMER_SEGMENT
		FROM CUSTOMER)
SELECT CUSTOMER_SEGMENT,
	COUNT(*) AS "number_of_customers"
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;

-- Q8. What are the top 3 purchased products within each category?

WITH ITEM_COUNTS AS
	(SELECT CATEGORY,
			ITEM_PURCHASED,
			COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
	  		ROW_NUMBER() OVER (PARTITION BY CATEGORY
																																																									ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEM_RANK
		FROM CUSTOMER
		GROUP BY CATEGORY,
			ITEM_PURCHASEd)
SELECT ITEM_RANK,
	CATEGORY,
	ITEM_PURCHASED,
	TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS;

-- Q10. What is the revenue contribution of each age group?

SELECT AGE_GROUP,
	SUM(PURCHASE_AMOUNT) AS REVENUE
FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY REVENUE DESC;

 